import React from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import {
  GitFork,
  GitPullRequest,
  CheckCircle2,
  ShieldAlert,
  Send,
  MessageSquareQuote,
  Activity,
  Layers,
} from "lucide-react";
import { fetchDashboardMetrics } from "@/lib/api/dashboard";
import { fetchReviewRuns } from "@/lib/api/reviews";
import { queryKeys } from "@/lib/query/queryKeys";
import { StatCard } from "@/components/ui/StatCard";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { LoadingState } from "@/components/ui/LoadingState";
import { ErrorState } from "@/components/ui/ErrorState";
import { EmptyState } from "@/components/ui/EmptyState";
import { formatDate, formatDuration, truncateSha } from "@/lib/utils/formatters";

export const DashboardPage: React.FC = () => {
  const {
    data: metrics,
    isLoading: isLoadingMetrics,
    error: metricsError,
    refetch: refetchMetrics,
  } = useQuery({
    queryKey: queryKeys.dashboard.metrics,
    queryFn: fetchDashboardMetrics,
  });

  const {
    data: recentRuns,
    isLoading: isLoadingRuns,
    error: runsError,
  } = useQuery({
    queryKey: queryKeys.reviews.list({ limit: 5 }),
    queryFn: () => fetchReviewRuns({ limit: 5 }),
  });

  if (isLoadingMetrics) {
    return <LoadingState title="Loading Review Dashboard" description="Aggregating platform metrics..." />;
  }

  if (metricsError) {
    return (
      <ErrorState
        title="Failed to Load Dashboard Metrics"
        message={metricsError instanceof Error ? metricsError.message : "Error fetching metrics"}
        onRetry={() => refetchMetrics()}
      />
    );
  }

  return (
    <div>
      <div className="page-header">
        <div>
          <h2 className="page-heading">Review Observability Dashboard</h2>
          <p className="page-subheading">
            Live metrics and audit verification state across connected repositories
          </p>
        </div>
      </div>

      {/* Observability Metrics Grid */}
      <div className="stats-grid">
        <StatCard
          label="Tracked Repositories"
          value={metrics?.total_repositories ?? 0}
          icon={<GitFork size={18} />}
          description="Monitored GitHub repositories"
        />
        <StatCard
          label="Pull Requests"
          value={metrics?.total_pull_requests ?? 0}
          icon={<GitPullRequest size={18} />}
          description="PRs ingested via webhooks"
        />
        <StatCard
          label="Review Runs"
          value={metrics?.total_review_runs ?? 0}
          icon={<Activity size={18} />}
          description={`${metrics?.active_review_runs ?? 0} active / running`}
        />
        <StatCard
          label="Total Findings"
          value={metrics?.total_findings ?? 0}
          icon={<Layers size={18} />}
          description="Candidates generated by specialists"
        />
        <StatCard
          label="Verified Findings"
          value={metrics?.verified_findings ?? 0}
          icon={<CheckCircle2 size={18} />}
          description="Confirmed by Critic pass"
        />
        <StatCard
          label="Rejected Findings"
          value={metrics?.rejected_findings ?? 0}
          icon={<ShieldAlert size={18} />}
          description="Suppressed false positives & nits"
        />
        <StatCard
          label="Published Comments"
          value={metrics?.published_findings ?? 0}
          icon={<Send size={18} />}
          description="Inline comments on GitHub PRs"
        />
        <StatCard
          label="Feedback Events"
          value={metrics?.total_feedback_events ?? 0}
          icon={<MessageSquareQuote size={18} />}
          description="Developer reactions & resolutions"
        />
      </div>

      {/* Recent Review Executions Section */}
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Recent Review Executions</h3>
          <Link to="/reviews" className="tab-btn" style={{ fontSize: "12px" }}>
            View All Reviews →
          </Link>
        </div>

        {isLoadingRuns ? (
          <LoadingState description="Loading recent review runs..." />
        ) : runsError ? (
          <ErrorState message="Could not load recent runs" />
        ) : !recentRuns || recentRuns.length === 0 ? (
          <EmptyState
            title="No review runs executed yet"
            description="When GitHub webhooks trigger code reviews, executions will appear here."
          />
        ) : (
          <div className="table-container">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Status</th>
                  <th>Repository</th>
                  <th>PR</th>
                  <th>Commit</th>
                  <th>Findings</th>
                  <th>Verified</th>
                  <th>Published</th>
                  <th>Duration</th>
                  <th>Created</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {recentRuns.map((run) => (
                  <tr key={run.id} data-testid={`recent-run-row-${run.id}`}>
                    <td>
                      <StatusBadge status={run.status} type="review" />
                    </td>
                    <td>{run.repository_full_name || "—"}</td>
                    <td>
                      {run.pr_number ? (
                        <Link
                          to={`/pull-requests/${run.pull_request_id}`}
                          style={{ color: "var(--primary)", fontWeight: 600 }}
                        >
                          #{run.pr_number}
                        </Link>
                      ) : (
                        "—"
                      )}
                    </td>
                    <td className="mono">{truncateSha(run.commit_sha)}</td>
                    <td>{run.findings_count}</td>
                    <td>
                      <span className="badge badge-verified">{run.verified_findings_count}</span>
                    </td>
                    <td>
                      <span className="badge badge-published">{run.published_findings_count}</span>
                    </td>
                    <td>{formatDuration(run.latency_seconds)}</td>
                    <td>{formatDate(run.created_at)}</td>
                    <td>
                      <Link
                        to={`/reviews/${run.id}`}
                        className="tab-btn"
                        style={{ padding: "4px 10px", fontSize: "12px", background: "var(--bg-surface-elevated)", borderRadius: "var(--radius-sm)" }}
                      >
                        Details
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};
