"""ReviewRun, findings, evidence, publication, and feedback read endpoints."""

import uuid
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.database.session import get_db_session
from app.schemas.dashboard import ReviewRunRead
from app.schemas.evidence import EvidenceModel
from app.schemas.finding import ReviewFinding
from app.schemas.publication import (
    FeedbackFilter,
    FeedbackResponse,
    PublicationResult,
)
from app.services.dashboard_service import DashboardService

router = APIRouter(prefix="/reviews", tags=["Reviews"])
dashboard_service = DashboardService()


@router.get(
    "",
    response_model=list[ReviewRunRead],
    summary="List Review Runs",
    description="Returns review run executions with status, timing, and findings count.",
)
async def list_review_runs(
    session: Annotated[AsyncSession, Depends(get_db_session)],
    pull_request_id: Annotated[
        uuid.UUID | None, Query(description="Filter by PR UUID")
    ] = None,
    status_filter: Annotated[
        str | None,
        Query(
            alias="status",
            description="Filter by status (QUEUED, RUNNING, COMPLETED, FAILED)",
        ),
    ] = None,
    limit: Annotated[int, Query(ge=1, le=500)] = 100,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> list[ReviewRunRead]:
    """List review executions."""
    return await dashboard_service.list_review_runs(
        session,
        pull_request_id=pull_request_id,
        status=status_filter,
        limit=limit,
        offset=offset,
    )


@router.get(
    "/{review_run_id}",
    response_model=ReviewRunRead,
    summary="Get Review Run",
    description="Returns single review run details by UUID.",
)
async def get_review_run(
    review_run_id: uuid.UUID,
    session: Annotated[AsyncSession, Depends(get_db_session)],
) -> ReviewRunRead:
    """Get single review run by ID."""
    run = await dashboard_service.get_review_run(session, review_run_id)
    if run is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"ReviewRun {review_run_id} not found",
        )
    return run


@router.get(
    "/{review_run_id}/findings",
    response_model=list[ReviewFinding],
    summary="List Review Run Findings",
    description="Returns canonical findings for a review run with attached evidence.",
)
async def list_review_run_findings(
    review_run_id: uuid.UUID,
    session: Annotated[AsyncSession, Depends(get_db_session)],
    verification_status: Annotated[
        str | None, Query(description="Filter by status (VERIFIED, REJECTED, etc.)")
    ] = None,
    severity: Annotated[
        str | None, Query(description="Filter by severity (CRITICAL, HIGH, etc.)")
    ] = None,
    issue_type: Annotated[
        str | None,
        Query(description="Filter by issue type (SECURITY, BUG_LOGIC, etc.)"),
    ] = None,
    limit: Annotated[int, Query(ge=1, le=500)] = 100,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> list[ReviewFinding]:
    """List findings generated by a review run."""
    run = await dashboard_service.get_review_run(session, review_run_id)
    if run is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"ReviewRun {review_run_id} not found",
        )
    return await dashboard_service.list_findings_for_run(
        session,
        review_run_id=review_run_id,
        verification_status=verification_status,
        severity=severity,
        issue_type=issue_type,
        limit=limit,
        offset=offset,
    )


@router.get(
    "/{review_run_id}/evidence",
    response_model=list[EvidenceModel],
    summary="List Review Run Evidence",
    description="Returns all grounded evidence items for a review run.",
)
async def list_review_run_evidence(
    review_run_id: uuid.UUID,
    session: Annotated[AsyncSession, Depends(get_db_session)],
) -> list[EvidenceModel]:
    """List evidence items for a review run."""
    run = await dashboard_service.get_review_run(session, review_run_id)
    if run is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"ReviewRun {review_run_id} not found",
        )
    return await dashboard_service.list_evidence_for_run(session, review_run_id)


@router.get(
    "/{review_run_id}/publications",
    response_model=list[PublicationResult],
    summary="List Review Run Publications",
    description="Returns GitHub review publication audit records for this run.",
)
async def list_review_run_publications(
    review_run_id: uuid.UUID,
    session: Annotated[AsyncSession, Depends(get_db_session)],
) -> list[PublicationResult]:
    """List GitHub publication audit records for a review run."""
    run = await dashboard_service.get_review_run(session, review_run_id)
    if run is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"ReviewRun {review_run_id} not found",
        )
    return await dashboard_service.list_publications_for_run(session, review_run_id)


@router.get(
    "/{review_run_id}/feedback",
    response_model=list[FeedbackResponse],
    summary="List Review Run Feedback",
    description="Returns developer and reviewer feedback linked to this review run.",
)
async def list_review_run_feedback(
    review_run_id: uuid.UUID,
    session: Annotated[AsyncSession, Depends(get_db_session)],
    limit: Annotated[int, Query(ge=1, le=500)] = 100,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> list[FeedbackResponse]:
    """List feedback recorded for a review run."""
    run = await dashboard_service.get_review_run(session, review_run_id)
    if run is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"ReviewRun {review_run_id} not found",
        )
    filter_params = FeedbackFilter(review_run_id=review_run_id)
    return await dashboard_service.list_feedback(
        session, filter_params=filter_params, limit=limit, offset=offset
    )
