"""0001_initial_schema

Revision ID: 01e79a94e743
Revises:
Create Date: 2026-09-29 15:00:14.576080

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01e79a94e743"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("github_repo_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "default_branch",
            sa.String(length=100),
            server_default="main",
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
    )
    op.create_index(
        op.f("ix_repositories_full_name"), "repositories", ["full_name"], unique=False
    )
    op.create_index(
        op.f("ix_repositories_github_repo_id"),
        "repositories",
        ["github_repo_id"],
        unique=True,
    )
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=False),
        sa.Column("base_sha", sa.String(length=40), nullable=False),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=30), server_default="open", nullable=False),
        sa.Column("additions", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deletions", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "changed_files_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_pull_requests_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pull_requests")),
        sa.UniqueConstraint(
            "repository_id", "pr_number", name="uq_pull_requests_repo_pr_number"
        ),
    )
    op.create_index(
        op.f("ix_pull_requests_repository_id"),
        "pull_requests",
        ["repository_id"],
        unique=False,
    )
    op.create_table(
        "review_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pull_request_id", sa.Uuid(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default="QUEUED", nullable=False
        ),
        sa.Column(
            "trigger_type",
            sa.String(length=30),
            server_default="WEBHOOK",
            nullable=False,
        ),
        sa.Column("total_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "total_cost_usd",
            sa.Numeric(precision=10, scale=4),
            server_default="0.0000",
            nullable=False,
        ),
        sa.Column("latency_seconds", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "review_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"],
            ["pull_requests.id"],
            name=op.f("fk_review_runs_pull_request_id_pull_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_runs")),
        sa.UniqueConstraint(
            "pull_request_id", "commit_sha", name="uq_review_runs_pr_commit"
        ),
    )
    op.create_index(
        "idx_review_runs_pr_status",
        "review_runs",
        ["pull_request_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_runs_pull_request_id"),
        "review_runs",
        ["pull_request_id"],
        unique=False,
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("review_run_id", sa.Uuid(), nullable=False),
        sa.Column("agent_name", sa.String(length=50), nullable=True),
        sa.Column("issue_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=10), server_default="RIGHT", nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("suggested_patch", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("raw_confidence", sa.Float(), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(length=50),
            server_default="UNVERIFIED",
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("critic_notes", sa.Text(), nullable=True),
        sa.Column("github_comment_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "publish_status",
            sa.String(length=30),
            server_default="UNPUBLISHED",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["review_run_id"],
            ["review_runs.id"],
            name=op.f("fk_findings_review_run_id_review_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index(
        "idx_findings_run_file",
        "findings",
        ["review_run_id", "file_path"],
        unique=False,
    )
    op.create_index(
        "idx_findings_run_status",
        "findings",
        ["review_run_id", "verification_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_findings_review_run_id"), "findings", ["review_run_id"], unique=False
    )
    op.create_table(
        "evidence_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("review_run_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_type", sa.String(length=50), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content_snippet", sa.Text(), nullable=False),
        sa.Column("rule_or_cve_id", sa.String(length=100), nullable=True),
        sa.Column("corroborating_tool", sa.String(length=50), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_evidence_items_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_run_id"],
            ["review_runs.id"],
            name=op.f("fk_evidence_items_review_run_id_review_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
    )
    op.create_index(
        "idx_evidence_items_run_file",
        "evidence_items",
        ["review_run_id", "file_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_items_finding_id"),
        "evidence_items",
        ["finding_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_items_review_run_id"),
        "evidence_items",
        ["review_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_items_review_run_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_finding_id"), table_name="evidence_items")
    op.drop_index("idx_evidence_items_run_file", table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_findings_review_run_id"), table_name="findings")
    op.drop_index("idx_findings_run_status", table_name="findings")
    op.drop_index("idx_findings_run_file", table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_review_runs_pull_request_id"), table_name="review_runs")
    op.drop_index("idx_review_runs_pr_status", table_name="review_runs")
    op.drop_table("review_runs")
    op.drop_index(op.f("ix_pull_requests_repository_id"), table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index(op.f("ix_repositories_github_repo_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_full_name"), table_name="repositories")
    op.drop_table("repositories")
    # ### end Alembic commands ###
