"""Canonical Pydantic v2 schemas for the review dashboard and frontend read APIs.

Defines response data contracts for:
- Repository listings and details
- Pull Request details and lifecycle progress
- ReviewRun status, pipeline timings, and cost metrics
- Dashboard overview and aggregate verification metrics
"""

import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class RepositoryRead(BaseModel):
    """Schema representing a tracked GitHub repository."""

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    id: uuid.UUID = Field(..., description="Unique repository identifier")
    github_repo_id: int = Field(..., description="GitHub repository numeric ID")
    full_name: str = Field(..., description="Repository full name (owner/repo)")
    default_branch: str = Field("main", description="Default repository branch")
    is_active: bool = Field(
        True, description="Whether the repository is actively monitored"
    )
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: datetime = Field(..., description="Last update timestamp")
    pull_requests_count: int = Field(
        0, description="Total ingested pull requests count"
    )


class PullRequestRead(BaseModel):
    """Schema representing an ingested GitHub pull request."""

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    id: uuid.UUID = Field(..., description="Unique pull request identifier")
    repository_id: uuid.UUID = Field(..., description="Associated repository UUID")
    repository_full_name: str | None = Field(
        None, description="Repository full name (owner/repo)"
    )
    pr_number: int = Field(..., description="GitHub pull request number")
    title: str = Field(..., description="Pull request title")
    author: str = Field(..., description="PR author GitHub username")
    base_sha: str = Field(..., description="Target base branch commit SHA")
    head_sha: str = Field(..., description="Source head branch commit SHA")
    state: str = Field("open", description="Pull request status state (open/closed)")
    additions: int = Field(0, description="Total line additions")
    deletions: int = Field(0, description="Total line deletions")
    changed_files_count: int = Field(0, description="Number of changed files in PR")
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: datetime = Field(..., description="Last update timestamp")
    review_runs_count: int = Field(
        0, description="Total review runs triggered for this PR"
    )
    latest_review_run_id: uuid.UUID | None = Field(
        None, description="Latest review run UUID"
    )
    latest_review_run_status: str | None = Field(
        None, description="Status of the latest review run"
    )


class ReviewRunRead(BaseModel):
    """Schema representing an individual review run pipeline execution."""

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    id: uuid.UUID = Field(..., description="Unique review run identifier")
    pull_request_id: uuid.UUID = Field(..., description="Associated pull request UUID")
    pr_number: int | None = Field(None, description="Pull request number")
    repository_full_name: str | None = Field(None, description="Repository full name")
    commit_sha: str = Field(..., description="Commit SHA analyzed by this review run")
    status: str = Field(
        "QUEUED",
        description="Current execution status (QUEUED, RUNNING, COMPLETED, FAILED)",
    )
    trigger_type: str = Field(
        "WEBHOOK", description="Trigger mechanism (WEBHOOK, MANUAL)"
    )
    total_tokens: int = Field(0, description="Total LLM tokens consumed")
    total_cost_usd: float = Field(0.0, description="Total LLM cost in USD")
    latency_seconds: float | None = Field(
        None, description="Total end-to-end execution duration in seconds"
    )
    review_plan: dict[str, Any] | None = Field(
        None, description="Review plan structure generated by planner agent"
    )
    error_log: str | None = Field(
        None, description="Error log details if review execution failed"
    )
    started_at: datetime | None = Field(
        None, description="Timestamp when review execution started"
    )
    completed_at: datetime | None = Field(
        None, description="Timestamp when review execution completed"
    )
    created_at: datetime = Field(..., description="Creation timestamp")
    findings_count: int = Field(0, description="Total candidate findings detected")
    verified_findings_count: int = Field(
        0, description="Total findings verified by the critic"
    )
    published_findings_count: int = Field(
        0, description="Total findings published to GitHub"
    )


class DashboardMetrics(BaseModel):
    """Schema for top-level review framework observability metrics."""

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    total_repositories: int = Field(0, description="Total repositories registered")
    total_pull_requests: int = Field(0, description="Total pull requests ingested")
    total_review_runs: int = Field(0, description="Total review runs executed")
    active_review_runs: int = Field(
        0, description="Currently running or queued review executions"
    )
    total_findings: int = Field(
        0, description="Total findings generated across all runs"
    )
    verified_findings: int = Field(0, description="Total findings verified by critic")
    rejected_findings: int = Field(
        0, description="Total findings rejected or suppressed"
    )
    published_findings: int = Field(0, description="Total findings published to GitHub")
    total_feedback_events: int = Field(
        0, description="Total reviewer feedback events collected"
    )
