"""Critic Agent prompt templates and prompt builder for evidence-grounded verification.

Instructs the LLM to conservatively verify or reject candidate review findings
grounded strictly in provided git diff hunks and deterministic evidence.
"""

from __future__ import annotations

from app.schemas.verification import VerificationContext

PROMPT_VERSION = "1.0.0"

CRITIC_SYSTEM_PROMPT = """You are the Senior Critic and Verification Agent in an automated code review system.
Your sole responsibility is to critically evaluate candidate findings generated by specialist agents and determine whether they are substantiated by concrete, visible repository evidence.

## CORE DIRECTIVES:
1. VERIFY, DO NOT GENERATE: You evaluate existing candidate claims. Do NOT invent new findings or report unrelated issues.
2. EVIDENCE-FIRST & CONSERVATIVE: A finding MUST NOT be marked VERIFIED unless the provided diff or surrounding code clearly demonstrates the defect.
3. SEPARATE FACT FROM INFERENCE:
   - FACT: Code explicitly visible in the diff or static analysis output.
   - INFERENCE: Plausible consequences of the visible code.
   - UNCERTAINTY: Assumptions about unobservable runtime configurations, external systems, or caller behavior.
4. REJECT SPECULATION & GENERIC ADVICE:
   - "Input validation should always be improved" -> REJECT.
   - Speculative vulnerability claims based solely on variable naming -> REJECT.
   - Claims contradicted by visible context -> REJECT.
5. CALIBRATE CONFIDENCE (0.0 to 1.0):
   - 0.85 - 1.00: Directly observable defect on changed line, supported by static analysis or obvious semantic flaw.
   - 0.70 - 0.84: Plausible defect grounded in the diff with minimal unverified assumptions.
   - 0.40 - 0.69: Weak inference, ambiguous intent, or missing context -> REJECT (insufficient evidence).
   - 0.00 - 0.39: Contradicted, incorrect assertion, or line outside modified region -> REJECT.
6. STRUCTURED OUTPUT: You must provide your analysis strictly in the requested JSON structure.
"""


def build_critic_user_prompt(context: VerificationContext) -> str:
    """Build a structured, bounded prompt for evaluating a single candidate finding."""
    finding = context.candidate_finding
    sections: list[str] = []

    sections.append(f"# CANDIDATE FINDING VERIFICATION (v{PROMPT_VERSION})")
    sections.append(
        f"**Repository:** {context.repository_full_name} | **Commit:** {context.commit_sha[:8]} | **Run ID:** {context.review_run_id}"
    )

    # 1. Candidate Finding Under Review
    sections.append("\n## CANDIDATE FINDING UNDER REVIEW")
    sections.append(f"- **Finding ID:** `{finding.finding_id}`")
    sections.append(
        f"- **Originating Agent:** `{context.agent_provenance or 'specialist'}`"
    )
    sections.append(f"- **Issue Type:** `{finding.issue_type.value}`")
    sections.append(f"- **Severity:** `{finding.severity.value}`")
    sections.append(f"- **Affected File:** `{finding.affected_file}`")
    sections.append(
        f"- **Line Number:** {finding.line_number} (Side: {finding.side.value})"
    )
    sections.append(
        f"- **Specialist Confidence:** {context.raw_confidence if context.raw_confidence is not None else 'N/A'}"
    )
    sections.append(f"- **Title:** {finding.title}")
    sections.append(f"- **Explanation:**\n  {finding.explanation}")
    sections.append(f"- **Recommendation:**\n  {finding.recommendation}")

    # 2. Code Diff Evidence
    sections.append("\n## CODE DIFF EVIDENCE")
    if context.hunk_header:
        sections.append(f"**Hunk Header:** `{context.hunk_header}`")

    if context.diff_snippet:
        sections.append("```diff")
        sections.append(context.diff_snippet)
        sections.append("```")
    else:
        sections.append("*No diff snippet available for this line.*")

    if context.surrounding_code:
        sections.append("\n**Surrounding Code Lines:**")
        sections.append("```python")
        sections.append(context.surrounding_code)
        sections.append("```")

    # 3. Static Analysis Corroboration
    sections.append("\n## CORROBORATING STATIC ANALYSIS EVIDENCE")
    if context.correlated_static_evidence:
        for idx, ev in enumerate(context.correlated_static_evidence, 1):
            tool = ev.corroborating_tool or "static_tool"
            rule = ev.rule_or_cve_id or "rule"
            sections.append(
                f"{idx}. **Tool:** `{tool}` | **Rule:** `{rule}` | **Lines:** {ev.start_line}-{ev.end_line}"
            )
            sections.append(f"   *Snippet:* `{ev.snippet}`")
    else:
        sections.append(
            "*No matching static analysis findings found at this file/line.*"
        )

    # 4. Deterministic Signals
    sections.append("\n## DETERMINISTIC SIGNALS")
    sections.append(f"- File in PR diff: {context.file_exists}")
    sections.append(f"- Cited line in PR diff: {context.line_in_diff}")
    sections.append(
        f"- Cited line was actively changed: {context.line_in_changed_hunk}"
    )

    # 5. Verification Task
    sections.append("\n## VERIFICATION TASK")
    sections.append("Analyze the candidate claim against the provided diff and code.")
    sections.append("Decide whether the claim is VERIFIED or REJECTED.")
    sections.append(
        "Provide calibrated_confidence (0.0 to 1.0), evidence_sufficiency, contradiction_detected, critic_notes, verification_reasons, and rejection_reasons."
    )

    return "\n".join(sections)
