"""Deterministic generator for top-level GitHub PR review summaries.

Constructs clear, audit-compliant markdown summaries detailing:
- Number of candidate findings detected vs. verified vs. rejected
- Breakdown by severity and issue category
- Unanchored findings (findings outside the changed line hunks) presented safely
- Zero leakage of raw prompts, credentials, or internal chain-of-thought
"""

from collections import Counter

from app.schemas.enums import IssueType, Severity
from app.schemas.finding import ReviewFinding


def generate_review_summary(
    total_findings: int,
    verified_findings: list[ReviewFinding],
    rejected_count: int = 0,
    unanchored_findings: list[ReviewFinding] | None = None,
    commit_sha: str | None = None,
) -> str:
    """Generate a clean, professional markdown summary for the overall PR review.

    Args:
        total_findings: Total candidate findings analyzed.
        verified_findings: List of verified findings eligible for publication.
        rejected_count: Total findings suppressed or dropped by verification.
        unanchored_findings: Verified findings that could not be anchored inline.
        commit_sha: Commit SHA for traceability.

    Returns:
        str: GitHub-ready markdown string.
    """
    unanchored = unanchored_findings or []
    verified_count = len(verified_findings)

    # Count by severity
    sev_counts = Counter(f.severity for f in verified_findings)
    # Count by category
    type_counts = Counter(f.issue_type for f in verified_findings)

    lines: list[str] = [
        "## 🤖 Automated Code Review Summary",
        "",
    ]

    if commit_sha:
        lines.append(f"**Target Commit:** `{commit_sha[:10]}`")
        lines.append("")

    # Status highlights
    if verified_count == 0:
        lines.extend(
            [
                "✅ **No verified issues found!** All automated verification checks passed.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                f"Found **{verified_count}** verified finding(s) requiring attention.",
                "",
            ]
        )

    # Overview Metrics Table
    lines.extend(
        [
            "### 📊 Review Overview",
            "",
            "| Metric | Count |",
            "| :--- | :--- |",
            f"| Candidate Findings Analyzed | {total_findings} |",
            f"| Verified Findings | **{verified_count}** |",
            f"| Rejected / Suppressed Findings | {rejected_count} |",
            f"| Inline Review Comments | {verified_count - len(unanchored)} |",
            f"| Unanchored Findings (in summary) | {len(unanchored)} |",
            "",
        ]
    )

    # Severity Breakdown
    if verified_count > 0:
        lines.extend(
            [
                "### 🎯 Severity Breakdown",
                "",
                "| Severity | Count |",
                "| :--- | :--- |",
                f"| 🚨 Critical | {sev_counts.get(Severity.CRITICAL, 0)} |",
                f"| ⚠️ High | {sev_counts.get(Severity.HIGH, 0)} |",
                f"| ⚡ Medium | {sev_counts.get(Severity.MEDIUM, 0)} |",
                f"| ℹ️ Low | {sev_counts.get(Severity.LOW, 0)} |",
                f"| 💡 Info | {sev_counts.get(Severity.INFO, 0)} |",
                "",
                "### 🏷️ Category Breakdown",
                "",
                "| Category | Count |",
                "| :--- | :--- |",
            ]
        )
        for issue_type in IssueType:
            count = type_counts.get(issue_type, 0)
            if count > 0:
                lines.append(f"| `{issue_type}` | {count} |")
        lines.append("")

    # Unanchored Findings Section
    if unanchored:
        lines.extend(
            [
                "---",
                "### 📌 Additional Findings (Outside Changed Lines)",
                "",
                "> The following verified issues were detected in affected files but outside the specific line ranges modified in this PR. They are reported here for awareness.",
                "",
            ]
        )
        for idx, finding in enumerate(unanchored, 1):
            lines.extend(
                [
                    f"#### {idx}. [{finding.severity}] {finding.title.strip()}",
                    f"- **Location:** `{finding.affected_file}:{finding.line_number}` (`{finding.side}`)",
                    f"- **Category:** `{finding.issue_type}`",
                    f"- **Issue:** {finding.explanation.strip()}",
                    f"- **Recommendation:** {finding.recommendation.strip()}",
                    "",
                ]
            )

    # Footer
    lines.extend(
        [
            "---",
            "*Generated by Agentic AI Code Reviewer. Evidence-based & verified.*",
        ]
    )

    return "\n".join(lines)
